Adcreo/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace Adcreo.Controllers
{
    public class AboutController : SurfaceController
    {
        private const string _aboutReasonsTopPartialViewName = "_AboutSection";
       
        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/About/{name}.cshtml";
        }
        public ActionResult RenderAboutSection()
        {
            return PartialView(PartialViewPath(_aboutReasonsTopPartialViewName));
        }
    }
}

Adcreo/Controllers/BusinessConsultancyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace Adcreo.Controllers
{
    public class BusinessConsultancyController : SurfaceController
    {
        private const string _businessConsultancyPartialViewName = "_BusinessConsultancy";
      
        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/Services/{name}.cshtml";
        }

        public ActionResult RenderBusinessConsultancySection()
        {
            return PartialView(PartialViewPath(_businessConsultancyPartialViewName));
        }
    }
}

Adcreo/Controllers/DesignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace Adcreo.Controllers
{
    public class DesignController : SurfaceController
    {
        private const string _designPartialViewName = "_DesignSection";

        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/Services/{name}.cshtml";
        }
        public ActionResult RenderDesignSection()
        {
            return PartialView(PartialViewPath(_designPartialViewName));
        }
    }
}

Adcreo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using Adcreo.Models;

namespace Adcreo.Controllers
{
    public class HomeController : SurfaceController
    {

        private const string _tagLinePartialViewName = "_ImageAndTagLine";
        private const string _weAreAboutPartialViewName = "_WeAreAbout";
        private const string _homeServicesPartialViewName = "_HomeServices";
        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/Home/{name}.cshtml";
        }

        public ActionResult RenderTagLine()
        {
            return PartialView(PartialViewPath(_tagLinePartialViewName));
        }

        public ActionResult RenderWeAreAbout()
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");
            string title = homePage.GetPropertyValue<string>("weAreAboutTitle");
            string bodyText = homePage.GetPropertyValue("weAreAboutBodyText").ToString();

            WeAreAboutModel model = new WeAreAboutModel(title, bodyText);
            return PartialView(PartialViewPath(_weAreAboutPartialViewName), model);
        }

        public ActionResult RenderHomeServices()
        {
            return PartialView(PartialViewPath(_homeServicesPartialViewName));
        }
    }
}

Adcreo/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace Adcreo.Controllers
{
    public class ServicesController : SurfaceController
    {
        private const string _servicesPartialViewName = "_ServicesSection";

        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/Services/{name}.cshtml";
        }
        public ActionResult RenderServicesSection()
        {
            return PartialView(PartialViewPath(_servicesPartialViewName));
        }
    }
}

Adcreo/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Adcreo.Models;
using Umbraco.Core.Models;
using System.Runtime.Caching;

namespace Adcreo.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string _headerPartialViewName = "_Header";
        private const string _footerPartialViewName = "_Footer";
        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/SiteLayout/{name}.cshtml";
        }

        public ActionResult RenderFooter()
        {
            List<NavigationListItemModel> nav = GetObjectFromCache<List<NavigationListItemModel>>("mainNav", 5, GetNavigationModelFromDatabase);
            return PartialView(PartialViewPath(_footerPartialViewName), nav);
        }

        /// <summary>
        /// Renders the top navigation on the _Header partial
        /// </summary>
        /// <returns>Partial view with a model</returns>
        public ActionResult RenderHeader()
        {
            List<NavigationListItemModel> nav = GetObjectFromCache<List<NavigationListItemModel>>("mainNav", 5, GetNavigationModelFromDatabase);
            return PartialView(PartialViewPath(_headerPartialViewName), nav);
        }

        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItemModel> GetNavigationModelFromDatabase()
        {
            const int HOME_PAGE_POSITION_IN_PATH = 1;
            int homePageId = int.Parse(CurrentPage.Path.Split(',')[HOME_PAGE_POSITION_IN_PATH]);
            IPublishedContent homePage = Umbraco.Content(homePageId);
            List<NavigationListItemModel> nav = new List<NavigationListItemModel>();
            nav.Add(new NavigationListItemModel(new NavigationLinkModel(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItemModel> GetChildNavigationList(dynamic page)
        {
            List<NavigationListItemModel> listItems = null;
            var childPages = page.Children.Where("Visible");
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItemModel>();
                foreach (var childPage in childPages)
                {
                    NavigationListItemModel listItem = new NavigationListItemModel(new NavigationLinkModel(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }

        /// <summary>
        /// A generic function for getting and setting objects to the memory cache.
        /// </summary>
        /// <typeparam name="T">The type of the object to be returned.</typeparam>
        /// <param name="cacheItemName">The name to be used when storing this object in the cache.</param>
        /// <param name="cacheTimeInMinutes">How long to cache this object for.</param>
        /// <param name="objectSettingFunction">A parameterless function to call if the object isn't in the cache and you need to set it.</param>
        /// <returns>An object of the type you asked for</returns>
        private static T GetObjectFromCache<T>(string cacheItemName, int cacheTimeInMinutes, Func<T> objectSettingFunction)
        {
            ObjectCache cache = MemoryCache.Default;
            var cachedObject = (T)cache[cacheItemName];
            if (cachedObject == null)
            {
                CacheItemPolicy policy = new CacheItemPolicy();
                policy.AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(cacheTimeInMinutes);
                cachedObject = objectSettingFunction();
                cache.Set(cacheItemName, cachedObject, policy);
            }
            return cachedObject;
        }
    }
}

Adcreo/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderAboutSection", "About");}

Adcreo/Views/Blog.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@
<br /><br /><br /><br /><br /><br /><br /><br />
<h1>Blog Page</h1>

Adcreo/Views/BusinessConsultancy.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}


@{ Html.RenderAction("RenderBusinessConsultancySection", "BusinessConsultancy");}

Adcreo/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@
<br /><br /><br /><br /><br /><br /><br /><br />
<h1>Contact Page</h1>

Adcreo/Views/Design.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderDesignSection", "Design");}

Adcreo/Views/Development.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

Adcreo/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

@{ Html.RenderAction("RenderTagLine", "Home");}
@{ Html.RenderAction("RenderWeAreAbout", "Home");}
@{ Html.RenderAction("RenderHomeServices", "Home");}

Adcreo/Views/Services.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@{ Html.RenderAction("RenderServicesSection", "Services");}

Adcreo/Views/Support.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

Adcreo/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title></title>
    <!-- CSS -->
    <!-- Bootstrap V4 alpha 6  -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Adcreo -->
    <link href="~/scss/main.css" rel="stylesheet" />
    <!-- IcoMoon Icon CSS -->
    <link href="~/Content/icomoon.css" rel="stylesheet" />
    <!-- Animate on Scroll -->
    <link href="~/Content/aos.css" rel="stylesheet" />
    <!-- Pick up a special fonts -->
    <link href="https://fonts.googleapis.com/css?family=Assistant|Roboto" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    @*<link href="~/Content/font-awesome.min.css" rel="stylesheet" />*@
    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/2991132.js"></script>
    <!-- End of HubSpot Embed Code -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    @{ Html.RenderAction("RenderHeader", "SiteLayout");}

    @RenderBody()

    @{ Html.RenderAction("RenderFooter", "SiteLayout");}

    <!-- Scripts -->
    <!-- jQuery 1st! (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- Bootstrap V4 alpha 6 -->
    <script src="~/Scripts/tether/tether.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Animate on Scroll -->
    <script src="~/Scripts/aos.js"></script>
    <!-- Adcreo -->
    <script src="~/Scripts/Adcreo.js"></script>

</body>
</html>